[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
identity_registry = "SAT1111111111111111111111111111111111111111"
reputation_registry = "SAT2111111111111111111111111111111111111111"
mandate_registry = "SAT3111111111111111111111111111111111111111"

[programs.devnet]
identity_registry = "SAT1111111111111111111111111111111111111111"
reputation_registry = "SAT2111111111111111111111111111111111111111"
mandate_registry = "SAT3111111111111111111111111111111111111111"

[programs.mainnet]
identity_registry = "SAT1111111111111111111111111111111111111111"
reputation_registry = "SAT2111111111111111111111111111111111111111"
mandate_registry = "SAT3111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"

[test]
startup_wait = 10000
